name: planticator
description: "Półprofesjonalna aplikacja do identyfikacji roślin, analizy siedlisk i fitosocjologii."
# Linia poniżej zapobiega przypadkowej publikacji w pub.dev
publish_to: 'none'

version: 1.0.0+1
share_plus: ^7.2.1
environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  intl: ^0.19.0
  sqflite: ^2.3.0
  path: ^1.9.1
  path_provider: ^2.1.0
  file_picker: ^8.0.0      # NOWOŚĆ: Dodane do obsługi przywracania bazy z pliku

  camera: ^0.11.0+1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  uuid: ^4.3.3
  timezone: ^0.9.2
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^3.0.0
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/grass.png
    - assets/ref/
    - assets/ref/zielne/owoce/
    - assets/ref/zielne/kwiat/
    - assets/ref/zielne/korzen/
    - assets/ref/drzewo/kora/
    - assets/ref/zielne/liscie/