// lib/models/description_schema.dart

/**
 * ============================================================================
 * DOKUMENTACJA REPOZYTORIUM - ROLA PLIKU I ZALEŻNOŚCI (Standard dla LLM)
 * ============================================================================
 * Rola pliku:
 * Dostarcza kompleksowe schematy, kategorie oraz cechy taksonomiczne z podziałem
 * na typy biologiczne (Drzewo, Krzew, Zielne, Grzyb, Mszaki). Pełni funkcję
 * bazy dydaktycznej (podpowiedzi edukacyjne), dostarczając opisy cech morfologicznych
 * oraz ścieżki do grafik referencyjnych ułatwiających terenową identyfikację.
 * Zaktualizowany o dynamiczne filtrowanie struktur na podstawie etapu fenologicznego.
 *
 * Zależności wewnętrzne (pliki z /lib):
 * - Brak bezpośrednich importów innych plików z /lib. Stanowi zamkniętą, niezależną
 * strukturę wiedzy morfologicznej (klucz oznaczeń), z której korzystają formularze
 * oraz ekrany identyfikacji (warstwa widoków).
 * ============================================================================
 */

class DescriptionCategory {
  final String number;
  final String title;
  final Map<String, List<String>> subCategories;
  final Map<String, String>? referenceImages;
  final Map<String, String>? imageDescriptions;

  DescriptionCategory({
    required this.number,
    required this.title,
    required this.subCategories,
    this.referenceImages,
    this.imageDescriptions,
  });
}

class SchemaGenerator {
  // POPRAWKA: Dodanie parametru phenologicalStage do inteligentnego filtrowania cech organów
  static List<DescriptionCategory> getForType(String type, {String? phenologicalStage}) {
    List<DescriptionCategory> categories;
    switch (type) {
      case "Grzyb": return _fungusSchema();
      case "Mszaki": return _bryophyteSchema();
      case "Zielne": categories = _herbaceousSchema(); break;
      case "Drzewo": categories = _treeSchema(); break;
      case "Krzew": categories = _shrubSchema(); break;
      default: categories = _herbaceousSchema(); break;
    }

    // Jeśli etap fenologiczny nie został określony, zwracamy pełny schemat bazowy
    if (phenologicalStage == null || phenologicalStage.isEmpty) {
      return categories;
    }

    List<DescriptionCategory> filtered = [];
    for (var cat in categories) {
      final title = cat.title.toLowerCase().trim();

      // REGÓŁA 1: W fazie czysto wegetatywnej ukrywamy wszelkie organy generatywne (kwiaty, owoce)
      if (phenologicalStage == "Wegetatywny") {
        if (title.contains("kwiat") || title.contains("owoc") || title.contains("rozrodcze")) {
          continue;
        }
      }
      // REGÓŁA 2: W fazie pączkowania i kwitnienia ukrywamy rozwinięte owoce, ale zostawiamy kwiaty
      else if (phenologicalStage == "Pączkowanie" || phenologicalStage == "Kwitnienie") {
        if (title.contains("owoc")) {
          continue;
        }
        // Dla drzew (kategoria połączona): odfiltrowujemy wyłącznie podkategorię "Typ" zawierającą owoce
        if (title == "organy rozrodcze") {
          final newSub = Map<String, List<String>>.from(cat.subCategories)..remove("Typ");
          filtered.add(DescriptionCategory(
            number: cat.number,
            title: cat.title,
            subCategories: newSub,
            referenceImages: cat.referenceImages,
            imageDescriptions: cat.imageDescriptions,
          ));
          continue;
        }
      }
      // REGÓŁA 3: W fazie owocowania i rozsiewania nasion ukrywamy świeże kwiaty, eksponujemy owoce
      else if (phenologicalStage == "Owocowanie" || phenologicalStage == "Rozsiewanie") {
        if (title == "kwiatostany" || title == "kwiaty i kwiatostany") {
          continue;
        }
        // Dla drzew: odfiltrowujemy podkategorie czysto kwitnieniowe z organów rozrodczych
        if (title == "organy rozrodcze") {
          final newSub = Map<String, List<String>>.from(cat.subCategories)
            ..remove("Kwitnienie")
            ..remove("Kwiatostany");
          filtered.add(DescriptionCategory(
            number: cat.number,
            title: cat.title,
            subCategories: newSub,
            referenceImages: cat.referenceImages,
            imageDescriptions: cat.imageDescriptions,
          ));
          continue;
        }
      }
      // REGÓŁA 4: W stanie spoczynku zimowego ukrywamy liście oraz organy generatywne (zostaje kora, pędy, pąki zimowe)
      else if (phenologicalStage == "Spoczynek") {
        if (title.contains("kwiat") || title.contains("owoc") || title.contains("rozrodcze") || title == "liście") {
          continue;
        }
      }

      filtered.add(cat);
    }
    return filtered;
  }

  static List<DescriptionCategory> _fungusSchema() {
  return [
    DescriptionCategory(
      number: "1",
      title: "Owocnik",
      subCategories: {
        "Typ owocnika": ["kapelusz", "lejkowaty", "maczugowaty", "kulisty", "miseczkowaty", "smardzowaty", "hubiasty", "galaretowaty", "soplowaty", "koralowaty"],
        "Powierzchnia": ["sucha", "lepka", "aksamitna", "łuskowata", "śluzowata", "gładka", "włóknista", "popękana", "brodawkowata"],
        "Brzeg": ["podwinięty", "prosty", "pofalowany", "prążkowany", "postrzępiony"],
        "Barwa": ["biała", "kremowa", "żółta", "pomarańczowa", "czerwona", "różowa", "fioletowa", "zielonkawa", "oliwkowa", "brązowa", "szara", "czarna"],
      },
      referenceImages: {
        "kapelusz": "assets/gress.png",
        "lejkowaty": "assets/gress.png",
        "maczugowaty": "assets/gress.png",
        "kulisty": "assets/gress.png",
        "miseczkowaty": "assets/gress.png",
        "smardzowaty": "assets/gress.png",
        "hubiasty": "assets/gress.png",
        "galaretowaty": "assets/gress.png",
        "soplowaty": "assets/gress.png",
        "koralowaty": "assets/gress.png",
        "sucha": "assets/gress.png",
        "lepka": "assets/gress.png",
        "aksamitna": "assets/gress.png",
        "łuskowata": "assets/gress.png",
        "śluzowata": "assets/gress.png",
        "gładka": "assets/gress.png",
        "włóknista": "assets/gress.png",
        "popękana": "assets/gress.png",
        "brodawkowata": "assets/gress.png",
        "podwinięty": "assets/gress.png",
        "prosty": "assets/gress.png",
        "pofalowany": "assets/gress.png",
        "prążkowany": "assets/gress.png",
        "postrzępiony": "assets/gress.png",
        "biała": "assets/gress.png",
        "kremowa": "assets/gress.png",
        "żółta": "assets/gress.png",
        "pomarańczowa": "assets/gress.png",
        "czerwona": "assets/gress.png",
        "różowa": "assets/gress.png",
        "fioletowa": "assets/gress.png",
        "zielonkawa": "assets/gress.png",
        "oliwkowa": "assets/gress.png",
        "brązowa": "assets/gress.png",
        "szara": "assets/gress.png",
        "czarna": "assets/gress.png",
      },
      imageDescriptions: {
        "kapelusz": "Owocnik posiada wyraźnie wykształcony kapelusz, zwykle osadzony na trzonie.",
        "lejkowaty": "Owocnik jest zagłębiony pośrodku i rozszerza się ku górze, przypominając lejek.",
        "maczugowaty": "Owocnik lub trzon jest wydłużony i rozszerzony ku górze, przypominając maczugę.",
        "kulisty": "Pokrój ma zarys zbliżony do kuli, o podobnej szerokości i wysokości.",
        "miseczkowaty": "Owocnik ma formę otwartej miseczki lub czarki.",
        "smardzowaty": "Owocnik ma wydłużoną główkę z charakterystycznymi jamkami i żebrami.",
        "hubiasty": "Owocnik wyrasta bocznie z drewna i tworzy półkę lub konsolę.",
        "galaretowaty": "Owocnik jest miękki, sprężysty i ma galaretowatą konsystencję.",
        "soplowaty": "Owocnik tworzy zwisające, wydłużone kolce lub soplowate struktury.",
        "koralowaty": "Owocnik jest silnie rozgałęziony i przypomina niewielki koral.",
        "sucha": "Powierzchnia jest sucha w dotyku i nie tworzy lepkiej ani śluzowatej warstwy.",
        "lepka": "Powierzchnia jest wyraźnie lepka w dotyku, szczególnie przy wilgotnej pogodzie.",
        "aksamitna": "Powierzchnia jest delikatnie, równomiernie owłosiona i przypomina aksamit.",
        "łuskowata": "Powierzchnia jest pokryta wyraźnymi łuskami lub odstającymi fragmentami tkanki.",
        "śluzowata": "Powierzchnię pokrywa wyraźna, śliska warstwa śluzu.",
        "gładka": "Powierzchnia jest równa, bez wyraźnych łusek, włosków, brodawek lub pęknięć.",
        "włóknista": "Kora lub powierzchnia pędu rozdziela się na podłużne włókna.",
        "popękana": "Powierzchnia rozpada się na pola oddzielone widocznymi pęknięciami.",
        "brodawkowata": "Powierzchnia jest pokryta drobnymi, wypukłymi brodawkami.",
        "podwinięty": "Brzeg jest zawinięty do dołu lub do wnętrza owocnika.",
        "prosty": "Drzewo ma jeden wyraźny, dominujący pień wyrastający od powierzchni gruntu.",
        "pofalowany": "Brzeg tworzy nieregularne, łagodne fale.",
        "prążkowany": "Na brzegu widoczne są promieniste prążki wynikające z budowy kapelusza.",
        "postrzępiony": "Brzeg jest nierówny, poszarpany lub podzielony na drobne fragmenty.",
        "biała": "Dominującą barwą obserwowanej cechy jest biała.",
        "kremowa": "Dominującą barwą obserwowanej cechy jest kremowa.",
        "żółta": "Dominującą barwą obserwowanej cechy jest żółta.",
        "pomarańczowa": "Dominującą barwą obserwowanej cechy jest pomarańczowa.",
        "czerwona": "Dominującą barwą obserwowanej części rośliny jest czerwień.",
        "różowa": "Dominującą barwą obserwowanej cechy jest różowa.",
        "fioletowa": "Dominującą barwą obserwowanej cechy jest fioletowa.",
        "zielonkawa": "Dominującą barwą obserwowanej cechy jest zielonkawa.",
        "oliwkowa": "Barwa jest zielonobrunatna lub oliwkowa.",
        "brązowa": "Dominującą barwą obserwowanej cechy jest brązowa.",
        "szara": "Dominującą barwą jest szarość lub szarawy odcień.",
        "czarna": "Kora jest bardzo ciemna, brunatnoczarna lub niemal czarna.",
      },
    ),
    DescriptionCategory(
      number: "2",
      title: "Hymenofor (spód)",
      subCategories: {
        "Typ": ["rurki", "blaszki", "kolce", "listewki", "gładki", "labiryntowy"],
        "Sposób przyrośnięcia blaszek": ["wolne", "zatokowato wycięte", "zbiegające", "przyrośnięte"],
        "Blaszki i pory": ["rzadkie", "średnie", "gęste", "bardzo drobne", "drobne", "duże", "okrągłe", "kanciaste", "nieregularne"],
        "Reakcja na ucisk": ["brak", "sinieje", "czerwienieje", "brunatnienie"],
      },
      referenceImages: {
        "rurki": "assets/gress.png",
        "blaszki": "assets/gress.png",
        "kolce": "assets/gress.png",
        "listewki": "assets/gress.png",
        "gładki": "assets/gress.png",
        "labiryntowy": "assets/gress.png",
        "wolne": "assets/gress.png",
        "zatokowato wycięte": "assets/gress.png",
        "zbiegające": "assets/gress.png",
        "przyrośnięte": "assets/gress.png",
        "rzadkie": "assets/gress.png",
        "średnie": "assets/gress.png",
        "gęste": "assets/gress.png",
        "bardzo drobne": "assets/gress.png",
        "drobne": "assets/gress.png",
        "duże": "assets/gress.png",
        "okrągłe": "assets/gress.png",
        "kanciaste": "assets/gress.png",
        "nieregularne": "assets/gress.png",
        "brak": "assets/gress.png",
        "sinieje": "assets/gress.png",
        "czerwienieje": "assets/gress.png",
        "brunatnienie": "assets/gress.png",
      },
      imageDescriptions: {
        "rurki": "Hymenofor tworzą liczne rurki zakończone porami widocznymi od spodu owocnika.",
        "blaszki": "Spód kapelusza tworzą cienkie, promieniście ułożone blaszki.",
        "kolce": "Obecne są powierzchniowe, kłujące wyrostki łatwiejsze do oddzielenia od pędu niż ciernie.",
        "listewki": "Spód tworzą grube, tępe fałdy przypominające blaszki, lecz będące częścią miąższu.",
        "gładki": "Cecha „gładki” opisuje wariant „typ” w kategorii „Hymenofor (spód)”.",
        "labiryntowy": "Pory są wydłużone i połączone, tworząc wzór przypominający labirynt.",
        "wolne": "Blaszki kończą się przed trzonem i nie są z nim połączone.",
        "zatokowato wycięte": "Blaszki przed trzonem tworzą charakterystyczne wcięcie lub zatokę.",
        "zbiegające": "Blaszki lub listewki schodzą wyraźnie w dół po powierzchni trzonu.",
        "przyrośnięte": "Blaszki dochodzą bezpośrednio do trzonu i są z nim połączone.",
        "rzadkie": "Elementy hymenoforu są rozmieszczone luźno, z wyraźnymi odstępami.",
        "średnie": "Gęstość elementów hymenoforu jest pośrednia między rzadką a gęstą.",
        "gęste": "Elementy hymenoforu są ułożone blisko siebie, z niewielkimi odstępami.",
        "bardzo drobne": "Pory są bardzo małe i zwykle trudno rozróżnić je pojedynczo bez zbliżenia.",
        "drobne": "Pory są małe, ale możliwe do rozpoznania gołym okiem.",
        "duże": "Pory są wyraźnie widoczne i mają stosunkowo dużą średnicę.",
        "okrągłe": "Pory mają regularny, zbliżony do koła kształt.",
        "kanciaste": "Pęd ma wyraźne podłużne krawędzie i wielokątny przekrój.",
        "nieregularne": "Pory różnią się kształtem i wielkością, bez wyraźnego regularnego wzoru.",
        "brak": "Cecha „reakcja na ucisk” nie występuje lub nie jest widoczna.",
        "sinieje": "Po uszkodzeniu lub ucisku tkanka zmienia barwę na niebieskawą lub siną.",
        "czerwienieje": "Po uszkodzeniu lub ucisku tkanka przyjmuje czerwonawy odcień.",
        "brunatnienie": "Po ucisku lub uszkodzeniu powierzchnia stopniowo brunatnieje.",
      },
    ),
    DescriptionCategory(
      number: "3",
      title: "Trzon",
      subCategories: {
        "Kształt": ["walcowaty", "bulwiasty", "wrzecionowaty", "maczugowaty", "odwrotnie maczugowaty"],
        "Wnętrze": ["pełne", "puste", "komorowe"],
        "Powierzchnia": ["gładka", "włóknista", "łuskowata", "siateczkowana", "kosmkowata", "chropowata"],
        "Pierścień": ["obecny (ruchomy)", "obecny (przyrośnięty)", "brak pierścienia", "podwójny"],
        "Pochwa u nasady": ["obecna", "brak pochwy", "szczątkowa"],
      },
      referenceImages: {
        "walcowaty": "assets/gress.png",
        "bulwiasty": "assets/gress.png",
        "wrzecionowaty": "assets/gress.png",
        "maczugowaty": "assets/gress.png",
        "odwrotnie maczugowaty": "assets/gress.png",
        "pełne": "assets/gress.png",
        "puste": "assets/gress.png",
        "komorowe": "assets/gress.png",
        "gładka": "assets/gress.png",
        "włóknista": "assets/gress.png",
        "łuskowata": "assets/gress.png",
        "siateczkowana": "assets/gress.png",
        "kosmkowata": "assets/gress.png",
        "chropowata": "assets/gress.png",
        "obecny (ruchomy)": "assets/gress.png",
        "obecny (przyrośnięty)": "assets/gress.png",
        "brak pierścienia": "assets/gress.png",
        "podwójny": "assets/gress.png",
        "obecna": "assets/gress.png",
        "brak pochwy": "assets/gress.png",
        "szczątkowa": "assets/gress.png",
      },
      imageDescriptions: {
        "walcowaty": "Trzon ma zbliżoną grubość na większości swojej długości.",
        "bulwiasty": "Podstawa trzonu jest wyraźnie zgrubiała i przypomina bulwę.",
        "wrzecionowaty": "Trzon jest najszerszy pośrodku i zwęża się ku obu końcom.",
        "maczugowaty": "Owocnik lub trzon jest wydłużony i rozszerzony ku górze, przypominając maczugę.",
        "odwrotnie maczugowaty": "Trzon jest szerszy przy podstawie i stopniowo zwęża się ku górze.",
        "pełne": "Wnętrze trzonu jest wypełnione zwartą tkanką.",
        "puste": "Wewnątrz trzonu znajduje się wyraźna pusta przestrzeń.",
        "komorowe": "Wnętrze trzonu zawiera kilka oddzielonych pustych komór.",
        "gładka": "Powierzchnia jest równa, bez wyraźnych łusek, włosków, brodawek lub pęknięć.",
        "włóknista": "Kora lub powierzchnia pędu rozdziela się na podłużne włókna.",
        "łuskowata": "Powierzchnia jest pokryta wyraźnymi łuskami lub odstającymi fragmentami tkanki.",
        "siateczkowana": "Powierzchnia posiada wypukły wzór przypominający drobną siatkę.",
        "kosmkowata": "Powierzchnia jest pokryta drobnymi kosmkami lub odstającymi włókienkami.",
        "chropowata": "Powierzchnia jest nierówna i wyczuwalnie szorstka.",
        "obecny (ruchomy)": "Pierścień jest dobrze wykształcony i może przesuwać się po trzonie.",
        "obecny (przyrośnięty)": "Pierścień jest trwale przyrośnięty do trzonu i nie przesuwa się.",
        "brak pierścienia": "Nie obserwuje się cechy określonej jako „brak pierścienia”.",
        "podwójny": "Pierścień ma dwuwarstwową lub wyraźnie podwójną budowę.",
        "obecna": "U podstawy trzonu widoczna jest pochwa będąca pozostałością osłony całkowitej.",
        "brak pochwy": "Nie obserwuje się cechy określonej jako „brak pochwy”.",
        "szczątkowa": "Pochwa jest słabo rozwinięta i widoczna jedynie jako fragmenty lub obrąbek.",
      },
    ),
    DescriptionCategory(
      number: "4",
      title: "Miąższ",
      subCategories: {
        "Zmiana barwy": ["nie zmienia", "sinieje", "czerwienieje", "czernieje", "zielenieje", "różowieje", "żółknie"],
        "Mleczko": ["białe", "pomarańczowe", "żółte", "czerwone", "bezbarwne"],
        "Zapach": ["brak", "grzybowy", "owocowy", "mączny", "nieprzyjemny", "anyżowy", "czosnkowy", "rzodkiewkowy", "ziemisty"],
      },
      referenceImages: {
        "nie zmienia": "assets/gress.png",
        "sinieje": "assets/gress.png",
        "czerwienieje": "assets/gress.png",
        "czernieje": "assets/gress.png",
        "zielenieje": "assets/gress.png",
        "różowieje": "assets/gress.png",
        "żółknie": "assets/gress.png",
        "białe": "assets/gress.png",
        "pomarańczowe": "assets/gress.png",
        "żółte": "assets/gress.png",
        "czerwone": "assets/gress.png",
        "bezbarwne": "assets/gress.png",
        "brak": "assets/gress.png",
        "grzybowy": "assets/gress.png",
        "owocowy": "assets/gress.png",
        "mączny": "assets/gress.png",
        "nieprzyjemny": "assets/gress.png",
        "anyżowy": "assets/gress.png",
        "czosnkowy": "assets/gress.png",
        "rzodkiewkowy": "assets/gress.png",
        "ziemisty": "assets/gress.png",
      },
      imageDescriptions: {
        "nie zmienia": "Miąższ po przecięciu lub uszkodzeniu zachowuje pierwotną barwę.",
        "sinieje": "Po uszkodzeniu lub ucisku tkanka zmienia barwę na niebieskawą lub siną.",
        "czerwienieje": "Po uszkodzeniu lub ucisku tkanka przyjmuje czerwonawy odcień.",
        "czernieje": "Miąższ po uszkodzeniu stopniowo przyjmuje bardzo ciemną lub czarną barwę.",
        "zielenieje": "Miąższ po uszkodzeniu przyjmuje zielonkawy odcień.",
        "różowieje": "Miąższ po uszkodzeniu przyjmuje różowy lub różowawy odcień.",
        "żółknie": "Miąższ po uszkodzeniu przyjmuje żółty odcień.",
        "białe": "Po uszkodzeniu wydziela się białe mleczko lub sok.",
        "pomarańczowe": "Po uszkodzeniu wydziela się pomarańczowe mleczko.",
        "żółte": "Po uszkodzeniu wydziela się żółte mleczko lub sok.",
        "czerwone": "Po uszkodzeniu wydziela się czerwone lub czerwonawe mleczko.",
        "bezbarwne": "Po uszkodzeniu wydziela się przezroczysty, bezbarwny płyn.",
        "brak": "Cecha „zapach” nie występuje lub nie jest widoczna.",
        "grzybowy": "Zapach jest typowy, łagodny i kojarzony ze świeżymi grzybami.",
        "owocowy": "Zapach przypomina dojrzałe owoce lub słodki aromat owocowy.",
        "mączny": "Zapach przypomina świeżą mąkę lub mokre ciasto.",
        "nieprzyjemny": "Zapach jest wyraźnie odpychający, ostry lub gnilny.",
        "anyżowy": "Zapach przypomina anyż, lukrecję lub słodkie przyprawy.",
        "czosnkowy": "Zapach wyraźnie przypomina czosnek.",
        "rzodkiewkowy": "Zapach jest ostry i przypomina rzodkiewkę.",
        "ziemisty": "Zapach przypomina wilgotną ziemię, ściółkę lub próchnicę.",
      },
    ),
  ];
}

  static List<DescriptionCategory> _bryophyteSchema() {
  return [
    DescriptionCategory(
      number: "1",
      title: "Gametofit (część zielona)",
      subCategories: {
        "Typ budowy": ["listkowaty (mech)", "plechowaty (wątrobowiec)"],
        "Pokrój": ["darnie luźne", "darnie zbite", "płożący", "wzniesiony pierzasto", "poduszkowaty", "pierzasty"],
        "Żeberko w listku": ["brak", "pojedyncze", "podwójne"],
      },
      referenceImages: {
        "listkowaty (mech)": "assets/gress.png",
        "plechowaty (wątrobowiec)": "assets/gress.png",
        "darnie luźne": "assets/gress.png",
        "darnie zbite": "assets/gress.png",
        "płożący": "assets/gress.png",
        "wzniesiony pierzasto": "assets/gress.png",
        "poduszkowaty": "assets/gress.png",
        "pierzasty": "assets/gress.png",
        "brak": "assets/gress.png",
        "pojedyncze": "assets/gress.png",
        "podwójne": "assets/gress.png",
      },
      imageDescriptions: {
        "listkowaty (mech)": "Gametofit tworzy łodyżkę z drobnymi listkami, typową dla większości mchów.",
        "plechowaty (wątrobowiec)": "Ciało ma postać spłaszczonej plechy bez typowego podziału na łodyżkę i listki.",
        "darnie luźne": "Pędy tworzą luźne skupienia, między którymi widoczne są wolne przestrzenie.",
        "darnie zbite": "Pędy rosną bardzo blisko siebie, tworząc zwartą darń.",
        "płożący": "Główne pędy rozrastają się poziomo po powierzchni podłoża.",
        "wzniesiony pierzasto": "Pęd główny jest wzniesiony i posiada regularne boczne rozgałęzienia.",
        "poduszkowaty": "Roślina tworzy zwartą, wypukłą kępę przypominającą poduszkę.",
        "pierzasty": "Pędy boczne są rozmieszczone po obu stronach osi, nadając roślinie pierzasty wygląd.",
        "brak": "Cecha „żeberko w listku” nie występuje lub nie jest widoczna.",
        "pojedyncze": "W listku widoczne jest jedno wyraźne żeberko biegnące wzdłuż jego osi.",
        "podwójne": "U nasady listka widoczne są dwa równoległe lub rozchodzące się żeberka.",
      },
    ),
    DescriptionCategory(
      number: "2",
      title: "Sporofit (część zarodniowa)",
      subCategories: {
        "Seta (trzonek)": ["krótka", "długa", "brak"],
        "Puszka": ["z wieczkiem", "otwierająca się szczelinami"],
      },
      referenceImages: {
        "krótka": "assets/gress.png",
        "długa": "assets/gress.png",
        "brak": "assets/gress.png",
        "z wieczkiem": "assets/gress.png",
        "otwierająca się szczelinami": "assets/gress.png",
      },
      imageDescriptions: {
        "krótka": "Seta jest krótka, dlatego puszka zarodni znajduje się blisko gametofitu.",
        "długa": "Seta jest wydłużona i wyraźnie wynosi puszkę zarodni ponad gametofit.",
        "brak": "Cecha „seta (trzonek)” nie występuje lub nie jest widoczna.",
        "z wieczkiem": "Puszka zarodni otwiera się przez odpadnięcie wieczka na jej szczycie.",
        "otwierająca się szczelinami": "Zarodnia uwalnia zarodniki przez podłużne szczeliny w ścianie puszki.",
      },
    ),
    DescriptionCategory(
      number: "3",
      title: "Siedlisko",
      subCategories: {
        "Podłoże": ["gleba", "kamienie", "kora drzew", "martwe drewno", "torfowisko", "woda"],
      },
      referenceImages: {
        "gleba": "assets/gress.png",
        "kamienie": "assets/gress.png",
        "kora drzew": "assets/gress.png",
        "martwe drewno": "assets/gress.png",
        "torfowisko": "assets/gress.png",
        "woda": "assets/gress.png",
      },
      imageDescriptions: {
        "gleba": "Roślina rośnie bezpośrednio na powierzchni gleby lub cienkiej warstwie próchnicy.",
        "kamienie": "Roślina zasiedla powierzchnię kamieni, głazów lub skał.",
        "kora drzew": "Roślina rośnie bezpośrednio na korze żywych drzew lub krzewów.",
        "martwe drewno": "Roślina zasiedla rozkładające się pnie, kłody, gałęzie lub pniaki.",
        "torfowisko": "Roślina rośnie w stale wilgotnym, kwaśnym środowisku torfowiskowym.",
        "woda": "Roślina rośnie w wodzie albo w strefie stale zalewanej.",
      },
    ),
  ];
}

  static List<DescriptionCategory> _shrubSchema() {
  return [
    DescriptionCategory(
      number: "1",
      title: "Pokrój i struktura",
      subCategories: {
        "Forma wzrostu": ["wzniesiony", "rozłożysty", "płożący", "zwisający", "pnący", "kulisty"],
        "Wysokość": ["niski (<0.5m)", "średni (0.5-2m)", "wysoki (>2m)"],
        "Gęstość korony": ["zwarta", "ażurowa", "bardzo gęsta"],
        "Sposób krzewienia": ["od nasady", "powyżej gruntu", "odroślowy"],
      },
      referenceImages: {
        "wzniesiony": "assets/gress.png",
        "rozłożysty": "assets/gress.png",
        "płożący": "assets/gress.png",
        "zwisający": "assets/gress.png",
        "pnący": "assets/gress.png",
        "kulisty": "assets/gress.png",
        "niski (<0.5m)": "assets/gress.png",
        "średni (0.5-2m)": "assets/gress.png",
        "wysoki (>2m)": "assets/gress.png",
        "zwarta": "assets/gress.png",
        "ażurowa": "assets/gress.png",
        "bardzo gęsta": "assets/gress.png",
        "od nasady": "assets/gress.png",
        "powyżej gruntu": "assets/gress.png",
        "odroślowy": "assets/gress.png",
      },
      imageDescriptions: {
        "wzniesiony": "Pędy rosną głównie pionowo lub ukośnie ku górze.",
        "rozłożysty": "Pędy szeroko rozchodzą się na boki, tworząc rozległy pokrój.",
        "płożący": "Główne pędy rozrastają się poziomo po powierzchni podłoża.",
        "zwisający": "Pędy są skierowane ku dołowi i wyraźnie przewieszają się.",
        "pnący": "Pędy wykorzystują podpory, aby wspinać się ponad podłoże.",
        "kulisty": "Pokrój ma zarys zbliżony do kuli, o podobnej szerokości i wysokości.",
        "niski (<0.5m)": "Roślina mieści się w klasie wysokości: niski (<0.5m).",
        "średni (0.5-2m)": "Roślina mieści się w klasie wysokości: średni (0.5-2m).",
        "wysoki (>2m)": "Roślina mieści się w klasie wysokości: wysoki (>2m).",
        "zwarta": "Korona jest gęsta, z niewielką liczbą prześwitów między pędami.",
        "ażurowa": "Korona jest luźna i posiada liczne prześwity między pędami.",
        "bardzo gęsta": "Pędy i liście tworzą bardzo zwartą, słabo prześwitującą koronę.",
        "od nasady": "Liczne główne pędy wyrastają bezpośrednio z okolicy nasady rośliny.",
        "powyżej gruntu": "Główne rozgałęzienia powstają wyraźnie ponad powierzchnią gruntu.",
        "odroślowy": "Nowe pędy wyrastają z korzeni lub podziemnych części rośliny wokół egzemplarza macierzystego.",
      },
    ),
    DescriptionCategory(
      number: "2",
      title: "Pędy i Kora",
      subCategories: {
        "Kora na starych pędach": ["gładka", "spękana", "łuszcząca się płatami", "włóknista", "bruzdowana", "korkowata"],
        "Pędy": ["obłe", "kanciaste", "spłaszczone", "listewkowate"],
        "Powierzchnia pędów": ["naga", "owłosione", "woskowana", "szczeciniasta", "lepka"],
        "Barwa pędów": ["zielona", "czerwona", "oliwkowa", "brunatna", "szara"],
        "Przetchlinki": ["brak przetchlinek", "wyraźne", "punktowe", "soczewkowate"],
        "Uzbrojenie": ["brak uzbrojenia", "ciernie", "kolce"],
        "Rdzeń": ["pełny", "pusty", "komorowy", "blaszkowaty"],
      },
      referenceImages: {
        "gładka": "assets/gress.png",
        "spękana": "assets/gress.png",
        "łuszcząca się płatami": "assets/gress.png",
        "włóknista": "assets/gress.png",
        "bruzdowana": "assets/gress.png",
        "korkowata": "assets/gress.png",
        "obłe": "assets/gress.png",
        "kanciaste": "assets/gress.png",
        "spłaszczone": "assets/gress.png",
        "listewkowate": "assets/gress.png",
        "naga": "assets/gress.png",
        "owłosione": "assets/gress.png",
        "woskowana": "assets/gress.png",
        "szczeciniasta": "assets/gress.png",
        "lepka": "assets/gress.png",
        "zielona": "assets/gress.png",
        "czerwona": "assets/gress.png",
        "oliwkowa": "assets/gress.png",
        "brunatna": "assets/gress.png",
        "szara": "assets/gress.png",
        "brak przetchlinek": "assets/gress.png",
        "wyraźne": "assets/gress.png",
        "punktowe": "assets/gress.png",
        "soczewkowate": "assets/gress.png",
        "brak uzbrojenia": "assets/gress.png",
        "ciernie": "assets/gress.png",
        "kolce": "assets/gress.png",
        "pełny": "assets/gress.png",
        "pusty": "assets/gress.png",
        "komorowy": "assets/gress.png",
        "blaszkowaty": "assets/gress.png",
      },
      imageDescriptions: {
        "gładka": "Powierzchnia jest równa, bez wyraźnych łusek, włosków, brodawek lub pęknięć.",
        "spękana": "Powierzchnia kory ma wyraźne pęknięcia i szczeliny.",
        "łuszcząca się płatami": "Kora odchodzi od pędu lub pnia większymi, cienkimi albo grubszymi płatami.",
        "włóknista": "Kora lub powierzchnia pędu rozdziela się na podłużne włókna.",
        "bruzdowana": "Na powierzchni widoczne są wyraźne podłużne bruzdy.",
        "korkowata": "Powierzchnia tworzy grubą, lekką i porowatą warstwę korkową.",
        "obłe": "Przekrój pędu jest zbliżony do koła i pozbawiony wyraźnych kantów.",
        "kanciaste": "Pęd ma wyraźne podłużne krawędzie i wielokątny przekrój.",
        "spłaszczone": "Pęd jest wyraźnie szerszy w jednej osi niż w drugiej.",
        "listewkowate": "Na pędzie występują podłużne wypukłe listewki lub żebra.",
        "naga": "Powierzchnia jest pozbawiona wyraźnych włosków.",
        "owłosione": "Powierzchnia jest pokryta wyraźnymi włoskami.",
        "woskowana": "Powierzchnię pokrywa warstwa woskowego nalotu, często nadająca sinawy odcień.",
        "szczeciniasta": "Powierzchnia jest pokryta sztywnymi, odstającymi szczecinkami.",
        "lepka": "Powierzchnia jest wyraźnie lepka w dotyku, szczególnie przy wilgotnej pogodzie.",
        "zielona": "Dominującą barwą obserwowanej części rośliny jest zieleń.",
        "czerwona": "Dominującą barwą obserwowanej części rośliny jest czerwień.",
        "oliwkowa": "Barwa jest zielonobrunatna lub oliwkowa.",
        "brunatna": "Barwa jest brunatna, od jasnobrązowej do ciemnobrązowej.",
        "szara": "Dominującą barwą jest szarość lub szarawy odcień.",
        "brak przetchlinek": "Nie obserwuje się cechy określonej jako „brak przetchlinek”.",
        "wyraźne": "Przetchlinki są łatwo widoczne gołym okiem na powierzchni pędu.",
        "punktowe": "Przetchlinki mają postać drobnych, punktowych znaków.",
        "soczewkowate": "Przetchlinki są wydłużone lub owalne i przypominają małe soczewki.",
        "brak uzbrojenia": "Nie obserwuje się cechy określonej jako „brak uzbrojenia”.",
        "ciernie": "Obecne są ostre, kłujące organy będące przekształconymi pędami lub liśćmi.",
        "kolce": "Obecne są powierzchniowe, kłujące wyrostki łatwiejsze do oddzielenia od pędu niż ciernie.",
        "pełny": "Wnętrze pędu jest wypełnione zwartą tkanką.",
        "pusty": "W osi pędu znajduje się wyraźna pusta przestrzeń.",
        "komorowy": "Wnętrze pędu jest podzielone przegrodami na kolejne komory.",
        "blaszkowaty": "Rdzeń tworzy charakterystyczne poprzeczne blaszki lub przegrody.",
      },
    ),
    DescriptionCategory(
      number: "3",
      title: "Pąki ",
      subCategories: {
        "Ułożenie": ["skrętoległe", "naprzeciwległe", "okółkowe"],
        "Kształt": ["kuliste", "jajowate", "wrzecionowate", "stożkowate"],
        "Łuski": ["nagusie (brak łusek)", "jedna łuska", "liczne łuski", "owłosione łuski"],
        "Powierzchnia pąków": ["naga", "owłosiona powierzchnia", "żywiczna", "lepka"],
      },
      referenceImages: {
        "skrętoległe": "assets/gress.png",
        "naprzeciwległe": "assets/gress.png",
        "okółkowe": "assets/gress.png",
        "kuliste": "assets/gress.png",
        "jajowate": "assets/gress.png",
        "wrzecionowate": "assets/gress.png",
        "stożkowate": "assets/gress.png",
        "nagusie (brak łusek)": "assets/gress.png",
        "jedna łuska": "assets/gress.png",
        "liczne łuski": "assets/gress.png",
        "owłosione łuski": "assets/gress.png",
        "naga": "assets/gress.png",
        "owłosiona powierzchnia": "assets/gress.png",
        "żywiczna": "assets/gress.png",
        "lepka": "assets/gress.png",
      },
      imageDescriptions: {
        "skrętoległe": "Liście lub pąki wyrastają pojedynczo na kolejnych węzłach, naprzemiennie wokół osi pędu.",
        "naprzeciwległe": "Dwa liście lub pąki wyrastają z jednego węzła po przeciwnych stronach pędu.",
        "okółkowe": "Co najmniej trzy liście lub pąki wyrastają z jednego węzła, tworząc okółek.",
        "kuliste": "Pąki mają kształt zbliżony do kuli.",
        "jajowate": "Pąki są szersze u nasady i zwężają się ku szczytowi.",
        "wrzecionowate": "Pąki są wydłużone, najszersze pośrodku i zwężone na obu końcach.",
        "stożkowate": "Pąki są szerokie u podstawy i regularnie zwężają się ku ostremu szczytowi.",
        "nagusie (brak łusek)": "Pąk nie jest osłonięty typowymi, zachodzącymi na siebie łuskami.",
        "jedna łuska": "Pąk jest osłonięty jedną dominującą łuską.",
        "liczne łuski": "Pąk jest osłonięty wieloma zachodzącymi na siebie łuskami.",
        "owłosione łuski": "Cecha „owłosione łuski” opisuje wariant „łuski” w kategorii „Pąki ”.",
        "naga": "Powierzchnia jest pozbawiona wyraźnych włosków.",
        "owłosiona powierzchnia": "Cecha „owłosiona powierzchnia” opisuje wariant „powierzchnia pąków” w kategorii „Pąki ”.",
        "żywiczna": "Powierzchnia jest pokryta żywicą lub ma wyraźnie żywiczny wygląd.",
        "lepka": "Powierzchnia jest wyraźnie lepka w dotyku, szczególnie przy wilgotnej pogodzie.",
      },
    ),
    DescriptionCategory(
      number: "4",
      title: "Liście",
      subCategories: {
        "Ulistnienie": ["skrętoległe", "naprzeciwległe", "okółkowe"],
        "Typ liścia": ["niepodzielne", "wrębne", "dzielne", "klapowate", "sieczne", "pierzasty", "dłoniasty"],
        "Kształt blaszki": ["igiełkowy", "równowąski", "lancetowaty", "eliptyczny", "jajowaty", "sercowaty", "łopatowaty", "owalny", "odwrotnie jajowaty", "strzałkowaty", "nerkowy"],
        "Brzeg Liścia": ["całobrzegi", "piłkowany", "ząbkowany", "karbowany", "falisty", "kolczasty", "podwójnie piłkowany", "podwójnie ząbkowany", "podwójnie karbowany"],
        "Powierzchnia": ["naga", "owłosiona (spód)", "owłosiona (obie strony)", "skórzasta", "woskowa"],
      },
      referenceImages: {
        "skrętoległe": "assets/gress.png",
        "naprzeciwległe": "assets/gress.png",
        "okółkowe": "assets/gress.png",
        "niepodzielne": "assets/gress.png",
        "wrębne": "assets/gress.png",
        "dzielne": "assets/gress.png",
        "klapowate": "assets/gress.png",
        "sieczne": "assets/gress.png",
        "pierzasty": "assets/gress.png",
        "dłoniasty": "assets/gress.png",
        "igiełkowy": "assets/gress.png",
        "równowąski": "assets/gress.png",
        "lancetowaty": "assets/gress.png",
        "eliptyczny": "assets/gress.png",
        "jajowaty": "assets/gress.png",
        "sercowaty": "assets/gress.png",
        "łopatowaty": "assets/gress.png",
        "owalny": "assets/gress.png",
        "odwrotnie jajowaty": "assets/gress.png",
        "strzałkowaty": "assets/gress.png",
        "nerkowy": "assets/gress.png",
        "całobrzegi": "assets/gress.png",
        "piłkowany": "assets/gress.png",
        "ząbkowany": "assets/gress.png",
        "karbowany": "assets/gress.png",
        "falisty": "assets/gress.png",
        "kolczasty": "assets/gress.png",
        "podwójnie piłkowany": "assets/gress.png",
        "podwójnie ząbkowany": "assets/gress.png",
        "podwójnie karbowany": "assets/gress.png",
        "naga": "assets/gress.png",
        "owłosiona (spód)": "assets/gress.png",
        "owłosiona (obie strony)": "assets/gress.png",
        "skórzasta": "assets/gress.png",
        "woskowa": "assets/gress.png",
      },
      imageDescriptions: {
        "skrętoległe": "Liście lub pąki wyrastają pojedynczo na kolejnych węzłach, naprzemiennie wokół osi pędu.",
        "naprzeciwległe": "Dwa liście lub pąki wyrastają z jednego węzła po przeciwnych stronach pędu.",
        "okółkowe": "Co najmniej trzy liście lub pąki wyrastają z jednego węzła, tworząc okółek.",
        "niepodzielne": "Blaszka liściowa pozostaje ciągła i nie jest głęboko podzielona na odcinki.",
        "wrębne": "Blaszka ma płytkie wcięcia, zwykle nieprzekraczające około jednej czwartej jej szerokości.",
        "dzielne": "Wcięcia blaszki są głębokie i sięgają mniej więcej do połowy odległości ku nerwowi głównemu.",
        "klapowate": "Blaszka tworzy wyraźne klapy oddzielone wcięciami, które nie dochodzą do nerwu głównego.",
        "sieczne": "Wcięcia są bardzo głębokie i dochodzą niemal do nerwu głównego lub nasady liścia.",
        "pierzasty": "Pędy boczne są rozmieszczone po obu stronach osi, nadając roślinie pierzasty wygląd.",
        "dłoniasty": "Liść lub jego główne części rozchodzą się promieniście z jednego punktu.",
        "igiełkowy": "Liść bardzo wąski, wydłużony i zwykle sztywny, przypominający igłę.",
        "równowąski": "Liść długi i wąski, o niemal jednakowej szerokości na większości długości.",
        "lancetowaty": "Liść wydłużony, najszerszy poniżej środka i zwężający się ku obu końcom.",
        "eliptyczny": "Blaszka ma kształt elipsy i jest najszersza mniej więcej w połowie długości.",
        "jajowaty": "Kształt przypomina jajko: jest szerszy u podstawy i zwęża się ku górze.",
        "sercowaty": "Blaszka przypomina serce i ma charakterystyczne wcięcie u nasady.",
        "łopatowaty": "Blaszka jest szersza i zaokrąglona przy szczycie, a zwęża się ku nasadzie.",
        "owalny": "Blaszka ma szeroko zaokrąglony, regularny obrys, nieco dłuższy niż szerszy.",
        "odwrotnie jajowaty": "Blaszka jest wyraźnie szersza bliżej szczytu niż przy nasadzie.",
        "strzałkowaty": "Nasada blaszki tworzy dwie ostre klapy skierowane w dół, jak grot strzały.",
        "nerkowy": "Blaszka jest szeroka, zaokrąglona i ma łagodne wcięcie u nasady.",
        "całobrzegi": "Brzeg blaszki jest gładki, bez ząbków, karbów i głębokich wcięć.",
        "piłkowany": "Brzeg ma ostre ząbki skierowane w stronę szczytu liścia.",
        "ząbkowany": "Brzeg ma ostre ząbki ustawione mniej więcej prostopadle do krawędzi.",
        "karbowany": "Brzeg tworzą regularne, zaokrąglone karby.",
        "falisty": "Krawędź liścia łagodnie faluje bez tworzenia wyraźnych ząbków.",
        "kolczasty": "Brzeg liścia posiada sztywne, ostre i kłujące zakończenia.",
        "podwójnie piłkowany": "Większe ząbki piłkowane są dodatkowo podzielone na mniejsze ząbki.",
        "podwójnie ząbkowany": "Każdy większy ząb brzegu posiada dodatkowe mniejsze ząbki.",
        "podwójnie karbowany": "Większe zaokrąglone karby są dodatkowo podzielone na drobniejsze karby.",
        "naga": "Powierzchnia jest pozbawiona wyraźnych włosków.",
        "owłosiona (spód)": "Włoski występują głównie na dolnej stronie blaszki liściowej.",
        "owłosiona (obie strony)": "Włoski występują zarówno na górnej, jak i dolnej stronie blaszki.",
        "skórzasta": "Blaszka jest gruba, sztywna i skórzasta w dotyku.",
        "woskowa": "Powierzchnia jest pokryta woskowym nalotem, często matowym lub sinawym.",
      },
    ),
    DescriptionCategory(
      number: "5",
      title: "Kwiaty i Kwiatostany",
      subCategories: {
        "Płeć": ["obupłciowe", "jednopłciowy"],
        "Symetria": ["promienista", "grzybiecista", "asymetryczna"],
        "Typ Kwiatostanu": ["grono", "baldachogrono", "wiecha", "baldach", "koszyczek", "kłos", "główka", "baldach podwójny", "kłos złożony", "sierpik", "wachlarz", "wiechotka złożona"],
        "Barwa korony": ["biała", "żółta", "różowa", "czerwona", "fioletowa", "zielonkawa"],
        "Liczba płatków": ["3", "4", "5", "6+"],
      },
      referenceImages: {
        "obupłciowe": "assets/gress.png",
        "jednopłciowy": "assets/gress.png",
        "promienista": "assets/gress.png",
        "grzybiecista": "assets/gress.png",
        "asymetryczna": "assets/gress.png",
        "grono": "assets/gress.png",
        "baldachogrono": "assets/gress.png",
        "wiecha": "assets/gress.png",
        "baldach": "assets/gress.png",
        "koszyczek": "assets/gress.png",
        "kłos": "assets/gress.png",
        "główka": "assets/gress.png",
        "baldach podwójny": "assets/gress.png",
        "kłos złożony": "assets/gress.png",
        "sierpik": "assets/gress.png",
        "wachlarz": "assets/gress.png",
        "wiechotka złożona": "assets/gress.png",
        "biała": "assets/gress.png",
        "żółta": "assets/gress.png",
        "różowa": "assets/gress.png",
        "czerwona": "assets/gress.png",
        "fioletowa": "assets/gress.png",
        "zielonkawa": "assets/gress.png",
        "3": "assets/gress.png",
        "4": "assets/gress.png",
        "5": "assets/gress.png",
        "6+": "assets/gress.png",
      },
      imageDescriptions: {
        "obupłciowe": "Cecha „obupłciowe” opisuje wariant „płeć” w kategorii „Kwiaty i Kwiatostany”.",
        "jednopłciowy": "Cecha „jednopłciowy” opisuje wariant „płeć” w kategorii „Kwiaty i Kwiatostany”.",
        "promienista": "Elementy kwiatu są rozmieszczone regularnie wokół środka i tworzą kilka osi symetrii.",
        "grzybiecista": "Kwiat ma tylko jedną płaszczyznę symetrii, z wyraźną stroną górną i dolną.",
        "asymetryczna": "Kwiat nie posiada wyraźnej płaszczyzny symetrii.",
        "grono": "Kwiaty na szypułkach są rozmieszczone wzdłuż wydłużonej osi głównej.",
        "baldachogrono": "Dolne szypułki są dłuższe od górnych, dzięki czemu kwiaty znajdują się na podobnej wysokości.",
        "wiecha": "Kwiatostan ma rozgałęzioną oś główną z licznymi bocznymi odgałęzieniami.",
        "baldach": "Szypułki kwiatowe wyrastają z jednego punktu i rozchodzą się jak pręty parasola.",
        "koszyczek": "Liczne drobne kwiaty siedzą na wspólnym, rozszerzonym dnie kwiatostanowym.",
        "kłos": "Kwiaty siedzą bezpośrednio na wydłużonej osi kwiatostanu.",
        "główka": "Drobne kwiaty są gęsto skupione na silnie skróconej osi.",
        "baldach podwójny": "Z osi głównej wyrastają mniejsze baldachy, a nie pojedyncze kwiaty.",
        "kłos złożony": "Na osi głównej znajdują się mniejsze kłoski zamiast pojedynczych kwiatów.",
        "sierpik": "Kolejne odgałęzienia kwiatostanu rozwijają się po jednej stronie, tworząc sierpowaty układ.",
        "wachlarz": "Odgałęzienia rozwijają się naprzemiennie po obu stronach, tworząc płaski wachlarz.",
        "wiechotka złożona": "Kwiatostan wierzchotkowy jest wielokrotnie rozgałęziony na kolejne osie boczne.",
        "biała": "Dominującą barwą obserwowanej cechy jest biała.",
        "żółta": "Dominującą barwą obserwowanej cechy jest żółta.",
        "różowa": "Dominującą barwą obserwowanej cechy jest różowa.",
        "czerwona": "Dominującą barwą obserwowanej części rośliny jest czerwień.",
        "fioletowa": "Dominującą barwą obserwowanej cechy jest fioletowa.",
        "zielonkawa": "Dominującą barwą obserwowanej cechy jest zielonkawa.",
        "3": "Kwiat posiada 3 wyraźnych płatków lub odpowiadających im odcinków korony.",
        "4": "Kwiat posiada 4 wyraźnych płatków lub odpowiadających im odcinków korony.",
        "5": "Kwiat posiada 5 wyraźnych płatków lub odpowiadających im odcinków korony.",
        "6+": "Kwiat posiada 6+ wyraźnych płatków lub odpowiadających im odcinków korony.",
      },
    ),
    DescriptionCategory(
      number: "6",
      title: "Owoce i Nasiona",
      subCategories: {
        "Typ owocu": ["jagoda", "pestkowy", "torebka", "skrzydlak", "orzech", "mieszek", "strąk", "zbiorowy", "pozorny"],
        "Barwa owocu": ["czerwona", "czarna", "niebieska", "żółta", "biała", "brązowa", "pomarańczowy", "fioletowy", "zielony"],
        "Ułożenie owoców": ["pojedynczo", "parami", "pęczki", "grona", "baldachy", "ukryte"],
        "Powierzcznia": ["gładka", "owłosiona", "woskowana", "kolczasta"],
        "Kształt": ["kulisty", "jajowaty", "wydłużony", "spłaszczony", "nieregularny"],
      },
      referenceImages: {
        "jagoda": "assets/gress.png",
        "pestkowy": "assets/gress.png",
        "torebka": "assets/gress.png",
        "skrzydlak": "assets/gress.png",
        "orzech": "assets/gress.png",
        "mieszek": "assets/gress.png",
        "strąk": "assets/gress.png",
        "zbiorowy": "assets/gress.png",
        "pozorny": "assets/gress.png",
        "czerwona": "assets/gress.png",
        "czarna": "assets/gress.png",
        "niebieska": "assets/gress.png",
        "żółta": "assets/gress.png",
        "biała": "assets/gress.png",
        "brązowa": "assets/gress.png",
        "pomarańczowy": "assets/gress.png",
        "fioletowy": "assets/gress.png",
        "zielony": "assets/gress.png",
        "pojedynczo": "assets/gress.png",
        "parami": "assets/gress.png",
        "pęczki": "assets/gress.png",
        "grona": "assets/gress.png",
        "baldachy": "assets/gress.png",
        "ukryte": "assets/gress.png",
        "gładka": "assets/gress.png",
        "owłosiona": "assets/gress.png",
        "woskowana": "assets/gress.png",
        "kolczasta": "assets/gress.png",
        "kulisty": "assets/gress.png",
        "jajowaty": "assets/gress.png",
        "wydłużony": "assets/gress.png",
        "spłaszczony": "assets/gress.png",
        "nieregularny": "assets/gress.png",
      },
      imageDescriptions: {
        "jagoda": "Owoc mięsisty, zwykle wielonasienny, o miękkiej owocni.",
        "pestkowy": "Owoc mięsisty zawierający jedną lub kilka twardych pestek.",
        "torebka": "Owoc suchy, który po dojrzeniu otwiera się i uwalnia nasiona.",
        "skrzydlak": "Suchy owoc wyposażony w błoniaste skrzydełko ułatwiające rozsiewanie przez wiatr.",
        "orzech": "Suchy, niepękający owoc o twardej lub zdrewniałej owocni.",
        "mieszek": "Suchy owoc otwierający się jednym szwem i uwalniający nasiona.",
        "strąk": "Suchy owoc otwierający się dwoma szwami, typowy dla roślin bobowatych.",
        "zbiorowy": "Owoc powstaje z wielu zalążni jednego kwiatu, tworząc skupienie drobnych owoców.",
        "pozorny": "W tworzeniu owocu uczestniczą również inne części kwiatu niż sama zalążnia.",
        "czerwona": "Dominującą barwą obserwowanej części rośliny jest czerwień.",
        "czarna": "Kora jest bardzo ciemna, brunatnoczarna lub niemal czarna.",
        "niebieska": "Dominującą barwą obserwowanej cechy jest niebieska.",
        "żółta": "Dominującą barwą obserwowanej cechy jest żółta.",
        "biała": "Dominującą barwą obserwowanej cechy jest biała.",
        "brązowa": "Dominującą barwą obserwowanej cechy jest brązowa.",
        "pomarańczowy": "Dominującą barwą obserwowanej cechy jest pomarańczowy.",
        "fioletowy": "Dominującą barwą obserwowanej cechy jest fioletowy.",
        "zielony": "Dominującą barwą obserwowanej cechy jest zielony.",
        "pojedynczo": "Owoce występują oddzielnie, bez tworzenia zwartego skupienia.",
        "parami": "Owoce występują najczęściej po dwa obok siebie.",
        "pęczki": "Owoce są zebrane po kilka w niewielkie, zwarte skupienia.",
        "grona": "Owoce są rozmieszczone wzdłuż wspólnej osi, tworząc grono.",
        "baldachy": "Szypułki owoców rozchodzą się z jednego punktu, tworząc układ baldachowaty.",
        "ukryte": "Owoce są częściowo zasłonięte przez liście, okrywy lub inne części rośliny.",
        "gładka": "Powierzchnia jest równa, bez wyraźnych łusek, włosków, brodawek lub pęknięć.",
        "owłosiona": "Powierzchnia jest pokryta widocznymi włoskami.",
        "woskowana": "Powierzchnię pokrywa warstwa woskowego nalotu, często nadająca sinawy odcień.",
        "kolczasta": "Powierzchnia posiada ostre, kłujące wyrostki.",
        "kulisty": "Pokrój ma zarys zbliżony do kuli, o podobnej szerokości i wysokości.",
        "jajowaty": "Kształt przypomina jajko: jest szerszy u podstawy i zwęża się ku górze.",
        "wydłużony": "Obiekt jest wyraźnie dłuższy niż szerszy.",
        "spłaszczony": "Obiekt jest wyraźnie spłaszczony w jednej osi.",
        "nieregularny": "Kształt nie odpowiada prostemu regularnemu zarysowi.",
      },
    ),
  ];
}

  static List<DescriptionCategory> _treeSchema() {
  return [
    DescriptionCategory(
      number: "1",
      title: "Pokrój i Pień",
      subCategories: {
        "Forma korony": ["stożkowata", "kolumnowa", "kopulasta", "zwisająca", "kulista", "jajowata", "odwrotnie jajowata", "malowniczy"],
        "Typ rozgałęziania": ["jednoosiowe", "wieloosiowe", "widlaste"],
        "Pień": ["kłoda", "prosty", "wielopniowy"],
      },
      referenceImages: {
        "stożkowata": "assets/ref/drzewo/pokroj/pien_stozek.png",
        "kolumnowa": "assets/ref/drzewo/pokroj/pien_kolumna.png",
        "kopulasta": "assets/ref/drzewo/pokroj/pien_kopulasta.png",
        "zwisająca": "assets/ref/drzewo/pokroj/pien_zwisajacy.png",
        "kulista": "assets/ref/drzewo/pokroj/pien_kulista.png",
        "jajowata": "assets/ref/drzewo/pokroj/pien_jajowaty.png",
        "odwrotnie jajowata": "assets/ref/drzewo/pokroj/pien_odwrotnie_jajowaty.png",
        "malowniczy": "assets/ref/drzewo/pokroj/pien_malowniczy.png",
        "jednoosiowe": "assets/ref/drzewo/pokroj/pien_jednoosiowe.png",
        "wieloosiowe": "assets/ref/drzewo/pokroj/pien_woeloosiowy.png",
        "widlaste": "assets/ref/drzewo/pokroj/pien_widlasty.png",
        "kłoda": "assets/ref/drzewo/pokroj/pien_kloda.png",
        "prosty": "assets/ref/drzewo/pokroj/pien_prosty.png",
        "wielopniowy": "assets/ref/drzewo/pokroj/pien_wielopniowy.png",
      },
      imageDescriptions: {
        "stożkowata": "Korona o szerokiej nasadzie, wyraźnie zwężająca się ku górze, przypominająca kształt stożka (typowa dla wielu iglaków).",
        "kolumnowa": "Korona wąska i wysoka, o zbliżonej szerokości na całej długości pnia.",
        "kopulasta": "Korona o zarysie kolistym, jednak wyraźnie spłaszczona w górnej części.",
        "zwisająca": "Forma, w której gałęzie i pędy boczne zwisają pionowo w dół (np. u wierzby płaczącej).",
        "kulista": "Korona ma regularny, zaokrąglony zarys zbliżony do kuli.",
        "jajowata": "Korona najszersza w dolnej lub środkowej części, o zaokrąglonym dole i szczycie.",
        "odwrotnie jajowata": "Korona jest węższa u dołu i wyraźnie rozszerza się w górnej części.",
        "malowniczy": "Korona składa się z większych oraz mniejszych skupisk liści, bardzo rozłożystych drzew.",
        "jednoosiowe": "Wzrost monopodialny, gdzie główny przewodnik rośnie pionowo i dominuje nad cieńszymi gałęziami bocznymi.",
        "wieloosiowe": "Pień rozwidla się nisko na kilka niemal równorzędnych konarów, tworząc rozłożystą strukturę bez pędu głównego.",
        "widlaste": "Pień rozwidla się na dwa równorzędne konary, tworząc równoległe korony.",
        "kłoda": "Pień, który na pewnej wysokości dzieli się na kilka głównych.",
        "prosty": "Drzewo wykształca tylko jeden, wyraźny pień główny wyrastający bezpośrednio z ziemi.",
        "wielopniowy": "Roślina posiada kilka pni o podobnej grubości, wyrastających obok siebie z tego samego systemu korzeniowego.",
      },
    ),
    DescriptionCategory(
      number: "2",
      title: "Kora",
      subCategories: {
        "Struktura": ["gładka", "spękana", "spękana podłużnie", "łuszcząca się płatami", "z przetchlinkami"],
        "Barwa korowiny": ["srebrzystobiała", "popielata", "oliwkowa", "miedziana", "brunatna", "czarna"],
      },
      referenceImages: {
        "gładka": "assets/ref/drzewo/kora/kora_gladka.png",
        "spękana": "assets/ref/drzewo/kora/kora_spekana.png",
        "spękana podłużnie": "assets/ref/drzewo/kora/kora_spekana_podluznie.png",
        "łuszcząca się płatami": "assets/ref/drzewo/kora/kora_odchodzaca.png",
        "z przetchlinkami": "assets/ref/drzewo/kora/kora_z_przetchlinakmi.png",
        "srebrzystobiała": "assets/ref/drzewo/kora/kora_srebrzystobiala.png",
        "popielata": "assets/ref/drzewo/kora/kora_popielata.png",
        "oliwkowa": "assets/ref/drzewo/kora/kora_oliwkowa.png",
        "miedziana": "assets/ref/drzewo/kora/kora_miedziana.png",
        "brunatna": "assets/ref/drzewo/kora/kora_brunatna.png",
        "czarna": "assets/ref/drzewo/kora/kora_czarna.png",
      },
      imageDescriptions: {
        "gładka": "Powierzchnia pnia pozbawiona wyraźnych spękań i wyniosłości.",
        "spękana": "Kora z wyraźnymi, nieregularnymi pęknięciami na powierzchni.",
        "spękana podłużnie": "Głębokie bruzdy biegnące wzdłuż pnia drzewa.",
        "łuszcząca się płatami": "Kora oddzielająca się od pnia w postaci cienkich lub grubych płatów (np. u platana lub brzozy).",
        "z przetchlinkami": "Obecność małych otworów (przetchlinek) służących do wymiany gazowej, widocznych często jako kreski lub kropki.",
        "srebrzystobiała": "Kora ma bardzo jasny, biały lub srebrzystobiały odcień.",
        "popielata": "Kora ma chłodny, szary lub popielaty odcień.",
        "oliwkowa": "Barwa jest zielonobrunatna lub oliwkowa.",
        "miedziana": "Kora ma ciepły, rdzawomiedziany odcień.",
        "brunatna": "Barwa jest brunatna, od jasnobrązowej do ciemnobrązowej.",
        "czarna": "Kora jest bardzo ciemna, brunatnoczarna lub niemal czarna.",
      },
    ),
    DescriptionCategory(
      number: "3",
      title: "Liście",
      subCategories: {
        "Trwałość": ["sezonowe (zrzucane)", "zimozielone"],
        "Ulistnienie": ["skrętoległe", "naprzeciwległe", "okółkowe"],
        "Typ liścia": ["niepodzielne", "wrębne", "dzielne", "klapowate", "sieczne"],
        "Kształt blaszki": ["igiełkowy", "równowąski", "lancetowaty", "eliptyczny", "jajowaty", "sercowaty", "łopatowaty", "owalny", "odwrotnie jajowaty", "strzałkowaty", "nerkowy"],
        "Brzeg Liścia": ["całobrzegi", "piłkowany", "ząbkowany", "karbowany", "falisty", "kolczasty", "podwójnie piłkowany", "podwójnie ząbkowany", "podwójnie karbowany"],
        "Unerwienie": ["pierzaste", "dłoniaste", "równoległe"],
      },
      referenceImages: {
        "sezonowe (zrzucane)": "assets/gress.png",
        "zimozielone": "assets/gress.png",
        "skrętoległe": "assets/ref/zielne/liscie/lisc_skretolegly.png",
        "naprzeciwległe": "assets/ref/zielne/liscie/liscie_naprzeciwlegle.png",
        "okółkowe": "assets/ref/zielne/liscie/lisc_okolkowe.png",
        "niepodzielne": "assets/ref/zielne/liscie/liscie_niepodzielne.png",
        "wrębne": "assets/ref/zielne/liscie/liscie_wrebne.png",
        "dzielne": "assets/ref/zielne/liscie/liscie_dzielne.png",
        "klapowate": "assets/ref/zielne/liscie/liscie_klapowate.png",
        "sieczne": "assets/ref/zielne/liscie/liscie_sieczne.png",
        "igiełkowy": "assets/ref/zielne/liscie/lisc_igiełkowy.png",
        "równowąski": "assets/ref/zielne/liscie/lisc_rownowaski.png",
        "lancetowaty": "assets/ref/zielne/liscie/lisc_lancetowaty.png",
        "eliptyczny": "assets/ref/zielne/liscie/lisc_eliptyczny.png",
        "jajowaty": "assets/ref/zielne/liscie/lisc_jajowaty.png",
        "sercowaty": "assets/ref/zielne/liscie/lisc_sercowaty.png",
        "łopatowaty": "assets/ref/zielne/liscie/lisc_lopatowaty.png",
        "owalny": "assets/ref/zielne/liscie/lisc_owalny.png",
        "odwrotnie jajowaty": "assets/ref/zielne/liscie/lisc_odwrotnie_jajowaty.png",
        "strzałkowaty": "assets/ref/zielne/liscie/lisc_strzalkowaty.png",
        "nerkowy": "assets/ref/zielne/liscie/lisc_nerkowy.png",
        "całobrzegi": "assets/ref/zielne/liscie/liscie_calobrzegi.png",
        "piłkowany": "assets/ref/zielne/liscie/lisc_pilkowany.png",
        "ząbkowany": "assets/ref/zielne/liscie/liscie_zabkowany.png",
        "karbowany": "assets/ref/zielne/liscie/lisc_karbowany.png",
        "falisty": "assets/ref/zielne/liscie/lisc_falisty.png",
        "kolczasty": "assets/ref/zielne/liscie/lisc_kolczasty.png",
        "podwójnie piłkowany": "assets/ref/zielne/liscie/lisc_podwojnie_pilkowany.png",
        "podwójnie ząbkowany": "assets/ref/zielne/liscie/lisc_podwojnie_zabkowany.png",
        "podwójnie karbowany": "assets/ref/zielne/liscie/lisc_podwojnie_karbowany.png",
        "pierzaste": "assets/ref/zielne/liscie/lisc_pierzasty.png",
        "dłoniaste": "assets/ref/zielne/liscie/lisc_dloniasty.png",
        "równoległe": "assets/ref/zielne/liscie/lisc_rownolegly.png",
      },
      imageDescriptions: {
        "sezonowe (zrzucane)": "Cecha „sezonowe (zrzucane)” opisuje wariant „trwałość” w kategorii „Liście”.",
        "zimozielone": "Cecha „zimozielone” opisuje wariant „trwałość” w kategorii „Liście”.",
        "skrętoległe": "Liście wyrastają pojedynczo z węzłów, tworząc spiralę wokół łodygi.",
        "naprzeciwległe": "Z jednego węzła wyrastają dwa liście położone po przeciwnych stronach łodygi.",
        "okółkowe": "Z jednego węzła wyrastają co najmniej trzy liście, tworząc pierścień (okółek) dookoła pędu.",
        "niepodzielne": "Blaszka liściowa o ciągłym obrysie, bez głębokich wcięć sięgających nerwu głównego.",
        "wrębne": "Wcięcia w blaszce są płytkie, sięgają nie dalej niż do 1/4 odległości od brzegu do nerwu głównego.",
        "dzielne": "Głębokie wcięcia sięgające do około połowy szerokości blaszki liściowej.",
        "klapowate": "Wcięcia blaszki sięgają głębiej niż u liścia wrębnego, ale nie dochodzą do połowy blaszki.",
        "sieczne": "Bardzo głębokie wcięcia sięgające niemal do samego nerwu głównego lub nasady liścia.",
        "igiełkowy": "Liście bardzo wąskie, sztywne i zwykle ostro zakończone, przypominające igły (np. u iglaków).",
        "równowąski": "Liść o niemal stałej szerokości na całej długości, znacznie dłuższy niż szerszy.",
        "lancetowaty": "Kształt wydłużony, najszerszy poniżej środka, zwężający się ku obu końcom (jak grot lancy).",
        "eliptyczny": "Kształt regularnej elipsy, najszerszy w połowie długości liścia.",
        "jajowaty": "Obrys przypominający jajko, z szerszą nasadą i węższym szczytem.",
        "sercowaty": "Blaszka z głębokim wcięciem u nasady, o kształcie przypominającym serce.",
        "łopatowaty": "Szeroki i zaokrąglony u szczytu, stopniowo zwężający się w stronę nasady.",
        "owalny": "Szeroko zaokrąglony kształt o długości nieco większej od szerokości.",
        "odwrotnie jajowaty": "Podobny do jajowatego, ale szerszy u góry (przy szczycie) niż przy nasadzie.",
        "strzałkowaty": "Nasada liścia posiada ostre klapy skierowane w dół, przypominając grot strzały.",
        "nerkowy": "Szeroki, zaokrąglony liść z głębokim, łagodnym wcięciem u nasady.",
        "całobrzegi": "Krawędź blaszki liściowej jest całkowicie gładka, bez żadnych wycięć.",
        "piłkowany": "Brzeg z ostrymi ząbkami skierowanymi wyraźnie w stronę szczytu liścia.",
        "ząbkowany": "Ząbki o równych bokach, skierowane prostopadle do krawędzi liścia.",
        "karbowany": "Brzeg z zaokrąglonymi ząbkami (karbami).",
        "falisty": "Brzeg nie tworzy ząbków, lecz faluje w płaszczyźnie blaszki.",
        "kolczasty": "Ząbki na brzegu liścia są zakończone sztywnymi, kłującymi wyrostkami.",
        "podwójnie piłkowany": "Większe ząbki piłkowane są dodatkowo podzielone na mniejsze ząbki.",
        "podwójnie ząbkowany": "System zębów, gdzie każdy ząb główny jest dodatkowo powcinany.",
        "podwójnie karbowany": "Krawędź z dużymi karbami, które same są dodatkowo delikatnie karbowane.",
        "pierzaste": "Jeden wyraźny nerw główny przebiega przez środek, a od niego odchodzą nerwy boczne.",
        "dłoniaste": "Kilka głównych nerwów o podobnej grubości rozchodzi się promieniście od nasady blaszki.",
        "równoległe": "Liczne, drobne nerwy biegną wzdłuż liścia niemal równolegle do siebie (typowe dla traw).",
      },
    ),
    DescriptionCategory(
      number: "4",
      title: "Organy rozrodcze",
      subCategories: {
        "Typ": ["szyszki", "owoce mięsiste", "skrzydlaki", "orzechy"],
        "Kwitnienie": ["kotki", "kwiaty okazałe", "niepozorne"],
        "System płciowy": ["jednopienne", "dwupienne", "obupłciowe"],
        "Kwiatostany": ["bazie", "wiechy", "baldachy", "pęczki", "szyszki męskie"],
        "Osadzenie": ["siedzące", "na szypułkach", "wzniesione", "zwisające"],
      },
      referenceImages: {
        "szyszki": "assets/gress.png",
        "owoce mięsiste": "assets/gress.png",
        "skrzydlaki": "assets/gress.png",
        "orzechy": "assets/gress.png",
        "kotki": "assets/gress.png",
        "kwiaty okazałe": "assets/gress.png",
        "niepozorne": "assets/gress.png",
        "jednopienne": "assets/gress.png",
        "dwupienne": "assets/gress.png",
        "obupłciowe": "assets/gress.png",
        "bazie": "assets/gress.png",
        "wiechy": "assets/gress.png",
        "baldachy": "assets/gress.png",
        "pęczki": "assets/gress.png",
        "szyszki męskie": "assets/gress.png",
        "siedzące": "assets/gress.png",
        "na szypułkach": "assets/gress.png",
        "wzniesione": "assets/gress.png",
        "zwisające": "assets/gress.png",
      },
      imageDescriptions: {
        "szyszki": "Cecha „szyszki” opisuje wariant „typ” w kategorii „Organy rozrodcze”.",
        "owoce mięsiste": "Cecha „owoce mięsiste” opisuje wariant „typ” w kategorii „Organy rozrodcze”.",
        "skrzydlaki": "Cecha „skrzydlaki” opisuje wariant „typ” w kategorii „Organy rozrodcze”.",
        "orzechy": "Cecha „orzechy” opisuje wariant „typ” w kategorii „Organy rozrodcze”.",
        "kotki": "Cecha „kotki” opisuje wariant „kwitnienie” w kategorii „Organy rozrodcze”.",
        "kwiaty okazałe": "Cecha „kwiaty okazałe” opisuje wariant „kwitnienie” w kategorii „Organy rozrodcze”.",
        "niepozorne": "Cecha „niepozorne” opisuje wariant „kwitnienie” w kategorii „Organy rozrodcze”.",
        "jednopienne": "Cecha „jednopienne” opisuje wariant „system płciowy” w kategorii „Organy rozrodcze”.",
        "dwupienne": "Cecha „dwupienne” opisuje wariant „system płciowy” w kategorii „Organy rozrodcze”.",
        "obupłciowe": "Cecha „obupłciowe” opisuje wariant „system płciowy” w kategorii „Organy rozrodcze”.",
        "bazie": "Cecha „bazie” opisuje wariant „kwiatostany” w kategorii „Organy rozrodcze”.",
        "wiechy": "Cecha „wiechy” opisuje wariant „kwiatostany” w kategorii „Organy rozrodcze”.",
        "baldachy": "Szypułki owoców rozchodzą się z jednego punktu, tworząc układ baldachowaty.",
        "pęczki": "Owoce są zebrane po kilka w niewielkie, zwarte skupienia.",
        "szyszki męskie": "Cecha „szyszki męskie” opisuje wariant „kwiatostany” w kategorii „Organy rozrodcze”.",
        "siedzące": "Cecha „siedzące” opisuje wariant „osadzenie” w kategorii „Organy rozrodcze”.",
        "na szypułkach": "Cecha „na szypułkach” opisuje wariant „osadzenie” w kategorii „Organy rozrodcze”.",
        "wzniesione": "Cecha „wzniesione” opisuje wariant „osadzenie” w kategorii „Organy rozrodcze”.",
        "zwisające": "Cecha „zwisające” opisuje wariant „osadzenie” w kategorii „Organy rozrodcze”.",
      },
    ),
  ];
}

  static List<DescriptionCategory> _herbaceousSchema() {
  return [
    DescriptionCategory(
      number: "1",
      title: "Pokrój rośliny",
      subCategories: {
        "System korzeniowy": ["palowy", "wiązkowy", "kłączowy", "bulwy", "cebula"],
        "Forma wzrostu": ["wzniesiona", "kępkowa", "rozetowa", "pełzająca", "pnąca", "wijąca"],
        "Wysokość": ["<10 cm", "10–30 cm", "30–100 cm", "<100 cm"],
      },
      referenceImages: {
        "palowy": "assets/ref/zielne/korzen/korzen_palowy.png",
        "wiązkowy": "assets/ref/zielne/korzen/korzen_wiazkowy.png",
        "kłączowy": "assets/ref/zielne/korzen/korzen_klacze.png",
        "bulwy": "assets/ref/zielne/korzen/korzen_bulwa.png",
        "cebula": "assets/ref/zielne/korzen/korzen_cebula.png",
        "wzniesiona": "assets/ref/zielne/korzen/korzen_wzniesiony.png",
        "kępkowa": "assets/ref/zielne/korzen/korzen_kepkowy.png",
        "rozetowa": "assets/ref/zielne/korzen/korzen_rozetowa.png",
        "pełzająca": "assets/ref/zielne/korzen/korzen_plozacy.png",
        "pnąca": "assets/gress.png",
        "wijąca": "assets/gress.png",
        "<10 cm": "assets/gress.png",
        "10–30 cm": "assets/gress.png",
        "30–100 cm": "assets/gress.png",
        "<100 cm": "assets/gress.png",
      },
      imageDescriptions: {
        "palowy": "System z jednym wyraźnym korzeniem głównym rosnącym pionowo w dół i mniejszymi korzeniami bocznymi.",
        "wiązkowy": "Liczne korzenie o podobnej grubości wyrastające pęczkiem z nasady pędu, typowe dla traw i roślin jednoliściennych.",
        "kłączowy": "Podziemny pęd rosnący poziomo, pełniący funkcję spichrzową, z którego wyrastają korzenie przybyszowe.",
        "bulwy": "Zgrubiałe części podziemne (pędu lub korzenia) magazynujące substancje zapasowe.",
        "cebula": "Podziemny organ spichrzowy o silnie skróconej łodydze i mięsistych liściach (np. u czosnku lub tulipana).",
        "wzniesiona": "Główne pędy rosną pionowo lub ukośnie ku górze.",
        "kępkowa": "Liczne pędy wyrastają blisko siebie i tworzą zwartą kępę.",
        "rozetowa": "Liście skupiają się przy powierzchni gruntu, tworząc przyziemną rozetę.",
        "pełzająca": "Pędy rozrastają się po podłożu i mogą zakorzeniać się w kolejnych węzłach.",
        "pnąca": "Roślina wspina się po podporach za pomocą pędów, wąsów lub innych struktur.",
        "wijąca": "Pęd owija się spiralnie wokół podpory.",
        "<10 cm": "Roślina osiąga zwykle mniej niż 10 cm wysokości.",
        "10–30 cm": "Roślina osiąga zwykle od 10 do 30 cm wysokości.",
        "30–100 cm": "Roślina osiąga zwykle od 30 do 100 cm wysokości.",
        "<100 cm": "Roślina według tej kategorii osiąga wysokość oznaczoną jako poniżej 100 cm.",
      },
    ),
    DescriptionCategory(
      number: "2",
      title: "Łodyga",
      subCategories: {
        "Typ łodygi": ["zielna", "zdrewniała", "półzdrewniała"],
        "Wnętrzne": ["puste", "pełna"],
        "Kształt (przekrój)": ["okrągły", "kanciasty", "bruzdowany", "spłaszczony"],
        "Powierzchnia": ["gładka", "owłosiona", "szorstka", "lepka", "woskowa"],
        "Włoski": ["proste", "gruczołowe", "haczykowate", "kutnerowate"],
        "Barwa": ["zielona", "brunatna", "czerwonawa", "sina"],
        "Mleczko": ["przezroczyste", "białe", "żółte", "czerwone"],
      },
      referenceImages: {
        "zielna": "assets/ref/zielne/lodyga/lodyga_zielna.png",
        "zdrewniała": "assets/ref/zielne/lodyga/lodyga_zdrewniala.png",
        "półzdrewniała": "assets/ref/zielne/lodyga/lodyga_polzdrewniala.png",
        "puste": "assets/ref/zielne/lodyga/lodyga_pusta.png",
        "pełna": "assets/ref/zielne/lodyga/lodyga_pelna.png",
        "okrągły": "assets/ref/zielne/lodyga/lodyga_okragla.png",
        "kanciasty": "assets/ref/zielne/lodyga/lodyga_kanciasta.png",
        "bruzdowany": "assets/ref/zielne/lodyga/lodyga_bruzdowata.png",
        "spłaszczony": "assets/ref/zielne/lodyga/lodyga_spalaszczona.png",
        "gładka": "assets/ref/zielne/lodyga/lodyga_gladka.png",
        "owłosiona": "assets/ref/zielne/lodyga/lodyga_owlosiona.png",
        "szorstka": "assets/ref/zielne/lodyga/lodyga_szorstka.png",
        "lepka": "assets/ref/zielne/lodyga/lodyga_lepka.png",
        "woskowa": "assets/ref/zielne/lodyga/lodyga_woskowa.png",
        "proste": "assets/ref/zielne/lodyga/lodyga_proste.png",
        "gruczołowe": "assets/ref/zielne/lodyga/lodyga_gruczolowa.png",
        "haczykowate": "assets/ref/zielne/lodyga/lodyga_haczykowate.png",
        "kutnerowate": "assets/ref/zielne/lodyga/ladyga_kuternowate.png",
        "zielona": "assets/ref/zielne/lodyga/lodyga_zielona.png",
        "brunatna": "assets/ref/zielne/lodyga/lodyga_brunatna.png",
        "czerwonawa": "assets/ref/zielne/lodyga/lodyga_czerwonawa.png",
        "sina": "assets/ref/zielne/lodyga/lodyga_sina.png",
        "przezroczyste": "assets/ref/zielne/lodyga/lodyga_przezroczyste.png",
        "białe": "assets/ref/zielne/lodyga/lodyga_biala.png",
        "żółte": "assets/ref/zielne/lodyga/lodyga_zolta.png",
        "czerwone": "assets/ref/zielne/lodyga/lodyga_czerwona.png",
      },
      imageDescriptions: {
        "zielna": "Łodyga miękka, soczysta, zwykle zielona, obumierająca po zakończeniu sezonu wegetacyjnego.",
        "zdrewniała": "Twarda łodyga pokryta warstwą korka lub kory, charakterystyczna dla krzewów i drzew.",
        "półzdrewniała": "Łodyga, której dolna część drewnieje i jest trwała, natomiast górna pozostaje zielna i obumiera na zimę.",
        "puste": "Wewnątrz trzonu znajduje się wyraźna pusta przestrzeń.",
        "pełna": "Cecha „pełna” opisuje wariant „wnętrzne” w kategorii „Łodyga”.",
        "okrągły": "Przekrój poprzeczny łodygi o kształcie zbliżonym do koła, bez wyraźnych krawędzi.",
        "kanciasty": "Obecność wyraźnych podłużnych krawędzi (np. łodyga czworokątna u roślin jasnotowatych).",
        "bruzdowany": "Powierzchnia łodygi z wyraźnymi, podłużnymi wgłębieniami i rynienkami.",
        "spłaszczony": "Łodyga wyraźnie szersza w jednej osi, często o formie wstęgowatej.",
        "gładka": "Powierzchnia pozbawiona włosków, brodawek i innych wyraźnych nierówności.",
        "owłosiona": "Pokryta różnego rodzaju włoskami (epidermą), które mogą pełnić funkcję ochronną.",
        "szorstka": "Nieprzyjemna w dotyku przez obecność sztywnych włosków lub wysycenie krzemionką.",
        "lepka": "Pokryta wydzieliną gruczołowatą, która klei się przy dotyku (często bariera dla owadów).",
        "woskowa": "Pokryta warstwą matowego nalotu (kutikuli), który można zetrzeć palcem; chroni przed parowaniem.",
        "proste": "Pojedyncze, nierozgałęzione włoski wyrastające z powierzchni łodygi.",
        "gruczołowe": "Włoski zakończone główką wydzielniczą, często zawierającą olejki eteryczne.",
        "haczykowate": "Sztywne włoski zakrzywione na końcach, ułatwiające roślinie wspinanie się lub czepianie.",
        "kutnerowate": "Bardzo gęste, splątane i miękkie włoski tworzące warstwę przypominającą filc.",
        "zielona": "Naturalna barwa łodygi wynikająca z obecności chlorofilu w tkankach.",
        "brunatna": "Ciemne zabarwienie, często pojawiające się u starszych roślin lub przy nasadzie pędu.",
        "czerwonawa": "Zabarwienie spowodowane obecnością antocyjanów, często reakcja na silne nasłonecznienie.",
        "sina": "Niebieskawo-zielony lub szary odcień nadany przez grubą warstwę wosku.",
        "przezroczyste": "Wypływający po uszkodzeniu bezbarwny, wodnisty sok roślinny.",
        "białe": "Gęsty, nieprzezroczysty płyn wypływający z rurek mlecznych po przerwaniu tkanki.",
        "żółte": "Sok o tej barwie często zawiera silne związki o właściwościach leczniczych, ale w dużych dawkach może być trujący.",
        "czerwone": "Rzadziej spotykany, bardzo charakterystyczny kolor. Rośliny te często zyskują przez to nazwy nawiązujące do krwi.",
      },
    ),
    DescriptionCategory(
      number: "3",
      title: "Liście",
      subCategories: {
        "Ulistnienie": ["skrętoległe", "naprzeciwległe", "okółkowe"],
        "Skupisko liścia": ["pojedyńcze", "podwójne", "potrójne", "wielonasadowe"],
        "Typ liścia": ["niepodzielne", "wrębne", "dzielne", "klapowate", "sieczne"],
        "Kształt blaszki": ["igiełkowy", "równowąski", "lancetowaty", "eliptyczny", "jajowaty", "sercowaty", "łopatowaty", "owalny", "odwrotnie jajowaty", "strzałkowaty", "nerkowy"],
        "Brzeg Liścia": ["całobrzegi", "piłkowany", "ząbkowany", "karbowany", "falisty", "kolczasty", "podwójnie piłkowany", "podwójnie ząbkowany", "podwójnie karbowany"],
        "Unerwienie": ["pierzaste", "dłoniaste", "równoległe"],
      },
      referenceImages: {
        "skrętoległe": "assets/ref/zielne/liscie/lisc_skretolegly.png",
        "naprzeciwległe": "assets/ref/zielne/liscie/liscie_naprzeciwlegle.png",
        "okółkowe": "assets/ref/zielne/liscie/lisc_okolkowe.png",
        "pojedyńcze": "assets/ref/zielne/liscie/lisc_okolkowe.png",
        "podwójne": "assets/ref/zielne/liscie/lisc_okolkowe.png",
        "potrójne": "assets/ref/zielne/liscie/lisc_okolkowe.png",
        "wielonasadowe": "assets/ref/zielne/liscie/lisc_okolkowe.png",
        "niepodzielne": "assets/ref/zielne/liscie/liscie_niepodzielne.png",
        "wrębne": "assets/ref/zielne/liscie/liscie_wrebne.png",
        "dzielne": "assets/ref/zielne/liscie/liscie_dzielne.png",
        "klapowate": "assets/ref/zielne/liscie/liscie_klapowate.png",
        "sieczne": "assets/ref/zielne/liscie/liscie_sieczne.png",
        "igiełkowy": "assets/ref/zielne/liscie/lisc_igiełkowy.png",
        "równowąski": "assets/ref/zielne/liscie/lisc_rownowaski.png",
        "lancetowaty": "assets/ref/zielne/liscie/lisc_lancetowaty.png",
        "eliptyczny": "assets/ref/zielne/liscie/lisc_eliptyczny.png",
        "jajowaty": "assets/ref/zielne/liscie/lisc_jajowaty.png",
        "sercowaty": "assets/ref/zielne/liscie/lisc_sercowaty.png",
        "łopatowaty": "assets/ref/zielne/liscie/lisc_lopatowaty.png",
        "owalny": "assets/ref/zielne/liscie/lisc_owalny.png",
        "odwrotnie jajowaty": "assets/ref/zielne/liscie/lisc_odwrotnie_jajowaty.png",
        "strzałkowaty": "assets/ref/zielne/liscie/lisc_strzalkowaty.png",
        "nerkowy": "assets/ref/zielne/liscie/lisc_nerkowy.png",
        "całobrzegi": "assets/ref/zielne/liscie/liscie_calobrzegi.png",
        "piłkowany": "assets/ref/zielne/liscie/lisc_pilkowany.png",
        "ząbkowany": "assets/ref/zielne/liscie/liscie_zabkowany.png",
        "karbowany": "assets/ref/zielne/liscie/lisc_karbowany.png",
        "falisty": "assets/ref/zielne/liscie/lisc_falisty.png",
        "kolczasty": "assets/ref/zielne/liscie/lisc_kolczasty.png",
        "podwójnie piłkowany": "assets/ref/zielne/liscie/lisc_podwojnie_pilkowany.png",
        "podwójnie ząbkowany": "assets/ref/zielne/liscie/lisc_podwojnie_zabkowany.png",
        "podwójnie karbowany": "assets/ref/zielne/liscie/lisc_podwojnie_karbowany.png",
        "pierzaste": "assets/ref/zielne/liscie/lisc_pierzasty.png",
        "dłoniaste": "assets/ref/zielne/liscie/lisc_dloniasty.png",
        "równoległe": "assets/ref/zielne/liscie/lisc_rownolegly.png",
      },
      imageDescriptions: {
        "skrętoległe": "Liście wyrastają pojedynczo z węzłów, tworząc spiralę wokół łodygi.",
        "naprzeciwległe": "Z jednego węzła wyrastają dwa liście położone po przeciwnych stronach łodygi.",
        "okółkowe": "Z jednego węzła wyrastają co najmniej trzy liście, tworząc pierścień (okółek) dookoła pędu.",
        "pojedyńcze": "Cecha „pojedyńcze” opisuje wariant „skupisko liścia” w kategorii „Liście”.",
        "podwójne": "U nasady listka widoczne są dwa równoległe lub rozchodzące się żeberka.",
        "potrójne": "Cecha „potrójne” opisuje wariant „skupisko liścia” w kategorii „Liście”.",
        "wielonasadowe": "Cecha „wielonasadowe” opisuje wariant „skupisko liścia” w kategorii „Liście”.",
        "niepodzielne": "Blaszka liściowa o ciągłym obrysie, bez głębokich wcięć sięgających nerwu głównego.",
        "wrębne": "Wcięcia w blaszce są płytkie, sięgają nie dalej niż do 1/4 odległości od brzegu do nerwu głównego.",
        "dzielne": "Głębokie wcięcia sięgające do około połowy szerokości blaszki liściowej.",
        "klapowate": "Wcięcia blaszki sięgają głębiej niż u liścia wrębnego, ale nie dochodzą do połowy blaszki.",
        "sieczne": "Bardzo głębokie wcięcia sięgające niemal do samego nerwu głównego lub nasady liścia.",
        "igiełkowy": "Liście bardzo wąskie, sztywne i zwykle ostro zakończone, przypominające igły (np. u iglaków).",
        "równowąski": "Liść o niemal stałej szerokości na całej długości, znacznie dłuższy niż szerszy.",
        "lancetowaty": "Kształt wydłużony, najszerszy poniżej środka, zwężający się ku obu końcom (jak grot lancy).",
        "eliptyczny": "Kształt regularnej elipsy, najszerszy w połowie długości liścia.",
        "jajowaty": "Obrys przypominający jajko, z szerszą nasadą i węższym szczytem.",
        "sercowaty": "Blaszka z głębokim wcięciem u nasady, o kształcie przypominającym serce.",
        "łopatowaty": "Szeroki i zaokrąglony u szczytu, stopniowo zwężający się w stronę nasady.",
        "owalny": "Szeroko zaokrąglony kształt o długości nieco większej od szerokości.",
        "odwrotnie jajowaty": "Podobny do jajowatego, ale szerszy u góry (przy szczycie) niż przy nasadzie.",
        "strzałkowaty": "Nasada liścia posiada ostre klapy skierowane w dół, przypominając grot strzały.",
        "nerkowy": "Szeroki, zaokrąglony liść z głębokim, łagodnym wcięciem u nasady.",
        "całobrzegi": "Krawędź blaszki liściowej jest całkowicie gładka, bez żadnych wycięć.",
        "piłkowany": "Brzeg z ostrymi ząbkami skierowanymi wyraźnie w stronę szczytu liścia.",
        "ząbkowany": "Ząbki o równych bokach, skierowane prostopadle do krawędzi liścia.",
        "karbowany": "Brzeg z zaokrąglonymi ząbkami (karbami).",
        "falisty": "Brzeg nie tworzy ząbków, lecz faluje w płaszczyźnie blaszki.",
        "kolczasty": "Ząbki na brzegu liścia są zakończone sztywnymi, kłującymi wyrostkami.",
        "podwójnie piłkowany": "Większe ząbki piłkowane są dodatkowo podzielone na mniejsze ząbki.",
        "podwójnie ząbkowany": "System zębów, gdzie każdy ząb główny jest dodatkowo powcinany.",
        "podwójnie karbowany": "Krawędź z dużymi karbami, które same są dodatkowo delikatnie karbowane.",
        "pierzaste": "Jeden wyraźny nerw główny przebiega przez środek, a od niego odchodzą nerwy boczne.",
        "dłoniaste": "Kilka głównych nerwów o podobnej grubości rozchodzi się promieniście od nasady blaszki.",
        "równoległe": "Liczne, drobne nerwy biegną wzdłuż liścia niemal równolegle do siebie (typowe dla traw).",
      },
    ),
    DescriptionCategory(
      number: "4",
      title: "Kwiatostany",
      subCategories: {
        "Typ Kwiatostanu": ["grono", "baldachogrono", "wiecha", "baldach", "koszyczek", "kłos", "główka", "baldach podwójny", "kłos złożony", "sierpik", "wachlarz", "wiechotka złożona"],
        "Zapach": ["brak", "słaby", "intensywny"],
        "Kolor": ["Biały", "Żółty", "Czerwony", "Różowy", "Fioletowy", "Niebieski", "Pomarańczowy", "Zielony"],
        "Liczba płatków": ["3", "4", "5", "6+"],
      },
      referenceImages: {
        "grono": "assets/ref/zielne/kwiat/kwiat_grono.png",
        "baldachogrono": "assets/ref/zielne/kwiat/kwiat_baldachogrono.png",
        "wiecha": "assets/ref/zielne/kwiat/kwiat_wiecha.png",
        "baldach": "assets/ref/zielne/kwiat/kwiat_baldach.png",
        "koszyczek": "assets/ref/zielne/kwiat/kwiat_koszyk.png",
        "kłos": "assets/ref/zielne/kwiat/kwiat_klos.png",
        "główka": "assets/ref/zielne/kwiat/kwiat_glowka.png",
        "baldach podwójny": "assets/ref/zielne/kwiat/kwiat_baldach_podwojny.png",
        "kłos złożony": "assets/ref/zielne/kwiat/kwiat_klos_zlozony.png",
        "sierpik": "assets/ref/zielne/kwiat/kwiat_sierpik.png",
        "wachlarz": "assets/ref/zielne/kwiat/kwiat_wachlarz.png",
        "wiechotka złożona": "assets/ref/zielne/kwiat/kwiat_wiechotka_wielo.PNG",
        "brak": "assets/ref/zielne/kwiat/kwiat_brak.png",
        "słaby": "assets/ref/zielne/kwiat/kwiat_slaby.png",
        "intensywny": "assets/ref/zielne/kwiat/kwiat_intensywny.png",

        "Biały": "assets/ref/zielne/kwiat/kwiat_bialy.png",
        "Żółty": "assets/ref/zielne/kwiat/kwiat_zolty.png",
        "Czerwony": "assets/ref/zielne/kwiat/kwiat_czerwony.png",
        "Różowy": "assets/ref/zielne/kwiat/kwiat_rozowy.png",
        "Fioletowy": "assets/ref/zielne/kwiat/kwiat_fioletowy.png",
        "Niebieski": "assets/ref/zielne/kwiat/kwiat_niebieski.png",
        "Pomarańczowy": "assets/ref/zielne/kwiat/kwiat_pomaranczowy.png",
        "Zielony": "assets/ref/zielne/kwiat/kwiat_zielony.png",

        "3": "assets/ref/zielne/kwiat/kwiat_3.png",
        "4": "assets/ref/zielne/kwiat/kwiat_4.png",
        "5": "assets/ref/zielne/kwiat/kwiat_5.png",
        "6+": "assets/ref/zielne/kwiat/kwiat_6.png",
      },
      imageDescriptions: {
        "grono": "Kwiaty osadzone na szypułkach o podobnej długości wzdłuż wydłużonej osi głównej (np. u konwalii).",
        "baldachogrono": "Odmiana grona, w której dolne szypułki są znacznie dłuższe od górnych, przez co wszystkie kwiaty znajdują się niemal na jednej wysokości.",
        "wiecha": "Złożony kwiatostan o rozgałęzionej osi głównej, gdzie odgałęzienia boczne są gronami lub kolejnymi wiechami.",
        "baldach": "Wszystkie szypułki kwiatowe wyrastają z jednego punktu na szczycie osi, przypominając pręty parasola (np. u czosnku).",
        "koszyczek": "Kwiaty siedzące osadzone na silnie skróconej, rozszerzonej osi tworzącej dno kwiatostanowe (charakterystyczny dla roślin astrowatych).",
        "kłos": "Kwiaty bezszypułkowe (siedzące) osadzone bezpośrednio wzdłuż wydłużonej osi głównej.",
        "główka": "Kwiaty siedzące bez szypyłki, gęsto skupione na skróconej, kulistej osi.",
        "baldach podwójny": "Z osi głównej wyrastają baldaszki (baldachy mniejszego rzędu) zamiast pojedynczych kwiatów (typowy dla selerowatych).",
        "kłos złożony": "Na osi głównej zamiast pojedynczych kwiatów osadzone są mniejsze kłoski o krótkich szypułkach.",
        "sierpik": "Kwiatostan wierzchotkowy, w którym kolejne osie boczne wyrastają zawsze po jednej stronie, zwijając się na kształt sierpa.",
        "wachlarz": "Odmiana wierzchotki, w której kwiaty wyrastają naprzemiennie po obu stronach osi, tworząc płaską strukturę przypominającą wachlarz.",
        "wiechotka złożona": "Rozbudowana struktura wierzchotkowa z wielokrotnymi odgałęzieniami bocznymi.",
        "brak": "Kwiaty nie wydzielają wyczuwalnego aromatu.",
        "słaby": "Zapach delikatny, wyczuwalny jedynie z bliskiej odległości.",
        "intensywny": "Silna woń wyczuwalna wyraźnie nawet z pewnej odległości od rośliny.",
        "Biały": "Korona kwiatu jest biała lub prawie biała.",
        "Żółty": "Korona kwiatu ma dominującą barwę żółtą.",
        "Czerwony": "Korona kwiatu ma dominującą barwę czerwoną.",
        "Różowy": "Korona kwiatu ma dominującą barwę różową.",
        "Fioletowy": "Korona kwiatu ma dominującą barwę fioletową.",
        "Niebieski": "Korona kwiatu ma dominującą barwę niebieską.",
        "Pomarańczowy": "Korona kwiatu ma dominującą barwę pomarańczową.",
        "Zielony": "Korona kwiatu ma dominującą barwę zieloną lub zielonkawą.",
        "3": "Kwiat posiada 3 wyraźnych płatków lub odpowiadających im odcinków korony.",
        "4": "Kwiat posiada 4 wyraźnych płatków lub odpowiadających im odcinków korony.",
        "5": "Kwiat posiada 5 wyraźnych płatków lub odpowiadających im odcinków korony.",
        "6+": "Kwiat posiada 6+ wyraźnych płatków lub odpowiadających im odcinków korony.",
      },
    ),
    DescriptionCategory(
      number: "5",
      title: "Owoce",
      subCategories: {
        "Typ owocu": ["jagoda", "pestkowiec", "orzech", "torebka", "niełupka", "strąk", "mieszek", "łuszczyna", "ziarniak", "skrzydlak"],
        "Barwa": ["zielona", "żółta", "pomarańczowa", "czerwona", "fioletowa", "niebieska", "czarna", "brunatna"],
        "Powierzchnia": ["gładka", "owłosiona", "kolczasta", "brodawkowata"],
      },
      referenceImages: {
        "jagoda": "assets/ref/zielne/owoce/owoce_jagoda.png",
        "pestkowiec": "assets/ref/zielne/owoce/owoc_pestkowiec.png",
        "orzech": "assets/ref/zielne/owoce/owoc_orzech.png",
        "torebka": "assets/ref/zielne/owoce/owoc_torebka.png",
        "niełupka": "assets/ref/zielne/owoce/owoc_nielupka.png",
        "strąk": "assets/ref/zielne/owoce/owoc_strak.png",
        "mieszek": "assets/ref/zielne/owoce/owoc_mieszek.png",
        "łuszczyna": "assets/ref/zielne/owoce/owoc_luszczyna.png",
        "ziarniak": "assets/ref/zielne/owoce/owoc_ziarniak.png",
        "skrzydlak": "assets/ref/zielne/owoce/owoc_skrzydlak.png",

        "zielona": "assets/ref/zielne/owoce/owoc_zielony.png",
        "żółta": "assets/ref/zielne/owoce/owoc_zolty.png",
        "pomarańczowa": "assets/ref/zielne/owoce/owoc_pomaranczowy.png",
        "czerwona": "assets/ref/zielne/owoce/owoc_czerwony.png",
        "fioletowa": "assets/ref/zielne/owoce/owoc_fioletowy.png",
        "niebieska": "assets/ref/zielne/owoce/owoc_niebieski.png",
        "czarna": "assets/ref/zielne/owoce/owoc_czarny.png",
        "brunatna": "assets/ref/zielne/owoce/owoc_brunatny.png",

        "gładka": "assets/ref/zielne/owoce/owoc_gladki.png",
        "owłosiona": "assets/ref/zielne/owoce/owoc_owlosiona.png",
        "kolczasta": "assets/ref/zielne/owoce/owoc_kolczasta.png",
        "brodawkowata": "assets/ref/zielne/owoce/owoc_brodawka.png",
      },
      imageDescriptions: {
        "jagoda": "Owoc mięsisty, wielonasienny, o cienkiej skórce.",
        "pestkowiec": "Owoc mięsisty z twardą, zdrewniałą pestką otaczającą nasiono.",
        "orzech": "Owoc suchy, niepękający pod naciskiem, o zdrewniałej owocni.",
        "torebka": "Owoc suchy, pękający, wewnątrz znajdują się liczne nasiona.",
        "niełupka": "Owoc suchy, jednonasienny, o skórzastej owocni.",
        "strąk": "Owoc suchy, pękający dwoma szwami z wieloma większymi nasionami.",
        "mieszek": "Suchy owoc otwierający się jednym szwem i uwalniający nasiona.",
        "łuszczyna": "Suchy owoc otwierający się dwiema klapami, z nasionami osadzonymi na przegrodzie.",
        "ziarniak": "Suchy, jednonasienny owoc, którego owocnia jest zrośnięta z łupiną nasienną.",
        "skrzydlak": "Suchy owoc wyposażony w błoniaste skrzydełko ułatwiające rozsiewanie przez wiatr.",
        "zielona": "Dominującą barwą obserwowanej części rośliny jest zieleń.",
        "żółta": "Dominującą barwą obserwowanej cechy jest żółta.",
        "pomarańczowa": "Dominującą barwą obserwowanej cechy jest pomarańczowa.",
        "czerwona": "Dominującą barwą obserwowanej części rośliny jest czerwień.",
        "fioletowa": "Dominującą barwą obserwowanej cechy jest fioletowa.",
        "niebieska": "Dominującą barwą obserwowanej cechy jest niebieska.",
        "czarna": "barwa jest bardzo ciemna, brunatnoczarna lub niemal czarna.",
        "brunatna": "Barwa jest brunatna, od jasnobrązowej do ciemnobrązowej.",
        "gładka": "Powierzchnia jest równa, bez wyraźnych łusek, włosków, brodawek lub pęknięć.",
        "owłosiona": "Powierzchnia jest pokryta widocznymi włoskami.",
        "kolczasta": "Powierzchnia posiada ostre, kłujące wyrostki.",
        "brodawkowata": "Powierzchnia jest pokryta drobnymi, wypukłymi brodawkami.",
      },
    ),
  ];
}
}